version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /myapp/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /myapp/docker-credentials/password
    DOCKER_REGISTRY_URL: /myapp/docker-registry/url

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing Node.js and npm...
      - n 18
      - npm config set registry https://registry.npmjs.org/

  pre_build:
    commands:
      - echo Logging in to Docker Registry...
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
      - export IMAGE_REPO_NAME=aws-my-portfolio-app-cicd
      - export REPOSITORY_URI=$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME
      - export IMAGE_TAG=v1
      - echo Building image $REPOSITORY_URI/$IMAGE_REPO_NAME:$IMAGE_TAG

  build:
    commands:
      - echo Build started on `date`
      - echo Packaging application into a zip file...
      - zip -r my-portfolio-app.zip * .[^.]* # Include all files and directories, including hidden files

  post_build:
    commands:
      - echo Uploading zip file to S3...
      - |
        if aws s3 ls s3://my-portfolio-artifacts 2>&1 | grep -q 'NoSuchBucket'
        then
          echo "Creating S3 bucket my-portfolio-artifacts"
          aws s3 mb s3://my-portfolio-artifacts --region ap-south-1
        fi
      - aws s3 cp my-portfolio-app.zip s3://my-portfolio-artifacts/builds/

artifacts:
  files:
    - '**/*'
  base-directory: '.'
  discard-paths: no
  exclude-patterns:
    - 'node_modules/**/*'
    - '.git/**/*'
    - '.gitignore'
    - 'README.md'
    - 'package-lock.json'
