version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /myapp/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /myapp/docker-credentials/password
    DOCKER_REGISTRY_URL: /myapp/docker-registry/url

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing Node.js and npm...
      - n 18
      - npm config set registry https://registry.npmjs.org/

  pre_build:
    commands:
      - echo Logging in to Docker Registry...
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
      - export IMAGE_REPO_NAME=aws-my-portfolio-app-cicd
      - export REPOSITORY_URI=$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME
      - export IMAGE_TAG=v1
      - echo Building image $REPOSITORY_URI/$IMAGE_REPO_NAME:$IMAGE_TAG

  build:
    commands:
      - echo Build started on `date`
      - echo Packaging application into a zip file...
      - zip -r my-portfolio-app.zip * .[^.]* # Include all files and directories, including hidden files
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI/$IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $REPOSITORY_URI/$IMAGE_REPO_NAME:$IMAGE_TAG $REPOSITORY_URI/$IMAGE_REPO_NAME:latest

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI/$IMAGE_REPO_NAME:$IMAGE_TAG
      - docker push $REPOSITORY_URI/$IMAGE_REPO_NAME:latest
      - echo Uploading zip file to S3 root location...
      - aws s3 cp my-portfolio-app.zip s3://aws-my-portfolio-app-cicd/my-portfolio-app/ # Upload zip file to the root of the bucket
      - echo Writing image definitions file...
      - printf '{"ImageURI":"%s", "Port":8000}' $REPOSITORY_URI/$IMAGE_REPO_NAME:$IMAGE_TAG > imageDefinitions.json
      - cat imageDefinitions.json

artifacts:
  files:
    - '**/*'
  base-directory: '.'
  discard-paths: no
  exclude-patterns:
    - 'node_modules/**/*'
    - '.git/**/*'
    - '.gitignore'
    - 'README.md'
    - 'package-lock.json'
